// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/resend-verification/:email": {
    params: {
      "email": string;
    };
  };
  "/resend-verification-email": {
    params: {};
  };
  "/verification-sent": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/organizations/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/organizations/new": {
    params: {};
  };
  "/dashboard/documents": {
    params: {};
  };
  "/dashboard/projects": {
    params: {};
  };
  "/dashboard/documents/new": {
    params: {};
  };
  "/dashboard/notifications": {
    params: {};
  };
  "/dashboard/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/projects/new": {
    params: {};
  };
  "/dashboard/invitations": {
    params: {};
  };
  "/dashboard/candidates": {
    params: {};
  };
  "/dashboard/recordings": {
    params: {};
  };
  "/dashboard/analytics": {
    params: {};
  };
  "/dashboard/meetings": {
    params: {};
  };
  "/dashboard/messages": {
    params: {};
  };
  "/dashboard/security": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
  "/dashboard/jobs": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/invite": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/demo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/resend-verification/:email" | "/resend-verification-email" | "/verification-sent" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/dashboard/organizations/:id" | "/dashboard/organizations/new" | "/dashboard/documents" | "/dashboard/projects" | "/dashboard/documents/new" | "/dashboard/notifications" | "/dashboard/projects/:id" | "/dashboard/projects/new" | "/dashboard/invitations" | "/dashboard/candidates" | "/dashboard/recordings" | "/dashboard/analytics" | "/dashboard/meetings" | "/dashboard/messages" | "/dashboard/security" | "/dashboard/settings" | "/dashboard/billing" | "/dashboard/profile" | "/dashboard/jobs" | "/support" | "/invite" | "/signup" | "/about" | "/login" | "/blog" | "/demo";
  };
  "routes/[.]well-known.appspecific.[com.chrome.devtools.json].tsx": {
    id: "routes/[.]well-known.appspecific.[com.chrome.devtools.json]";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/resend-verification.$email.tsx": {
    id: "routes/resend-verification.$email";
    page: "/resend-verification/:email";
  };
  "routes/resend-verification-email.tsx": {
    id: "routes/resend-verification-email";
    page: "/resend-verification-email";
  };
  "routes/verification-sent.tsx": {
    id: "routes/verification-sent";
    page: "/verification-sent";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/verify-email.tsx": {
    id: "routes/verify-email";
    page: "/verify-email";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/organizations/:id" | "/dashboard/organizations/new" | "/dashboard/documents" | "/dashboard/projects" | "/dashboard/documents/new" | "/dashboard/notifications" | "/dashboard/projects/:id" | "/dashboard/projects/new" | "/dashboard/invitations" | "/dashboard/candidates" | "/dashboard/recordings" | "/dashboard/analytics" | "/dashboard/meetings" | "/dashboard/messages" | "/dashboard/security" | "/dashboard/settings" | "/dashboard/billing" | "/dashboard/profile" | "/dashboard/jobs";
  };
  "routes/dashboard.organizations.$id.tsx": {
    id: "routes/dashboard.organizations.$id";
    page: "/dashboard/organizations/:id";
  };
  "routes/dashboard.organizations.new.tsx": {
    id: "routes/dashboard.organizations.new";
    page: "/dashboard/organizations/new";
  };
  "routes/dashboard.documents._index.tsx": {
    id: "routes/dashboard.documents._index";
    page: "/dashboard/documents";
  };
  "routes/dashboard.projects._index.tsx": {
    id: "routes/dashboard.projects._index";
    page: "/dashboard/projects";
  };
  "routes/dashboard.documents.new.tsx": {
    id: "routes/dashboard.documents.new";
    page: "/dashboard/documents/new";
  };
  "routes/dashboard.notifications.tsx": {
    id: "routes/dashboard.notifications";
    page: "/dashboard/notifications";
  };
  "routes/dashboard.projects.$id.tsx": {
    id: "routes/dashboard.projects.$id";
    page: "/dashboard/projects/:id";
  };
  "routes/dashboard.projects.new.tsx": {
    id: "routes/dashboard.projects.new";
    page: "/dashboard/projects/new";
  };
  "routes/dashboard.invitations.tsx": {
    id: "routes/dashboard.invitations";
    page: "/dashboard/invitations";
  };
  "routes/dashboard.candidates.tsx": {
    id: "routes/dashboard.candidates";
    page: "/dashboard/candidates";
  };
  "routes/dashboard.recordings.tsx": {
    id: "routes/dashboard.recordings";
    page: "/dashboard/recordings";
  };
  "routes/dashboard.analytics.tsx": {
    id: "routes/dashboard.analytics";
    page: "/dashboard/analytics";
  };
  "routes/dashboard.meetings.tsx": {
    id: "routes/dashboard.meetings";
    page: "/dashboard/meetings";
  };
  "routes/dashboard.messages.tsx": {
    id: "routes/dashboard.messages";
    page: "/dashboard/messages";
  };
  "routes/dashboard.security.tsx": {
    id: "routes/dashboard.security";
    page: "/dashboard/security";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
  "routes/dashboard.billing.tsx": {
    id: "routes/dashboard.billing";
    page: "/dashboard/billing";
  };
  "routes/dashboard.profile.tsx": {
    id: "routes/dashboard.profile";
    page: "/dashboard/profile";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.jobs.tsx": {
    id: "routes/dashboard.jobs";
    page: "/dashboard/jobs";
  };
  "routes/support.tsx": {
    id: "routes/support";
    page: "/support";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/invite.tsx": {
    id: "routes/invite";
    page: "/invite";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/demo.tsx": {
    id: "routes/demo";
    page: "/demo";
  };
};